chore: update policy documents
openebs/mayastor-chart-donotuse pull request #1
Opened 2024-05-08 14:35 UTC by Abhinandan-Purkait

### Changes

- Update GOVERNANCE
- Update CONTRIBUTING.md
- Update CODE_OF_CONDUCT.md
- Update MAINTAINERS

2024-05-08 14:40 UTC, tiagolobocastro commented
hmm not sure if we should add to this repo, gh_pages branch is special, not sure if it might cause issues.
Maybe we should just go ahead and mark this repo as internal so it's no visible since this is just used for testing?

2024-05-08 15:56 UTC, edrob999 approved these changes
:thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

2024-05-08 16:23 UTC, tiagolobocastro requested changes
Let's add this to develop and make develop the main branch

2024-05-09 10:58 UTC, niladrih approved these changes

2024-05-09 13:23 UTC, tiagolobocastro approved these changes

2024-05-09 13:24 UTC, avishnu approved these changes

2024-05-09 13:25 UTC, merged